### PR TITLE
Uses ChartBuilder for treemap

### PR DESCRIPTION
**Pull request by emilianbold**
Two remarks here:

* if I don't do any column processing for the treemap chart and expect for the columns to be prepared then more preparation needs to be done in the calling classes. I might have to add some util to help with some parts...

* I like how this looks:

```java
....rowColumns("ids")
                .labelColumns("Label")
                .dataColumns(/* parent: */ "Parent")
                .sizeColumn(/* values: */ "MarketCap")
                .detailColumns(/* text: */ "Change")
                .colorColumn(/* marker.colors: */ "ChangeAsNumber")
                .layout(1043, 500, false);
```

but I think users will need some Javadoc to know which column does what.

### CODE REVIEW

**Comment by nielsgron** [comment]
In your syntax suggestion I am not clear on your use of "ids", "Label" and "Parent".  Do you mean this? ...

ChartBuilder treemapBuilder = ChartBuilder.createBuilder()
                .dataTable(treemapTable)
                .chartType(ChartBuilder.CHART_TYPE.TREEMAP)
                .dataColumns("Sector", "Industry")
                .rowColumns("Ticker")
                .sizeColumn("MarketCap")
                .colorColumn("ChangeAsNumber")
                .labelColumns("Ticker", "Change")
                .detailColumns("Sector, "Industry", "Company", "Ticker", "Price", "Change")
                .layout(500, 200, false);

**Comment by emilianbold** [comment]
In `ChartsTreemap` I'm using this:

```java
 ChartBuilder stockBuilder = ChartBuilder.createBuilder()
                .dataTable(treemapTable)
                .chartType(ChartBuilder.CHART_TYPE.TREEMAP)
                .rowColumns("ids")
                .labelColumns("Label")
                .dataColumns(/* parent: */ "Parent")
                .sizeColumn(/* values: */ "MarketCap")
                .detailColumns(/* text: */ "Change")
                .colorColumn(/* marker.colors: */ "ChangeAsNumber")
                .layout(1043, 500, false);
```

which is how I figured I should map the treemap concepts to the `ChartBuilder` APIs. Not sure if that is correct. 

In the above code `ids` are generated while `Label` is a column obtained by joining `Ticker` with `Industry` and `Sector`.

**Comment by nielsgron** [comment]
The treemapTable does not have columns named "ids", "Label" and "Parent", so where are you getting these?  The treemap also needs to know the "Sector" and "Industry" columns, but you are not providing them to the ChartBuilder, so how does it know to use them?

**Comment by emilianbold** [comment]
Those columns are generated by me in `ChartsTreemap`. Previously I allowed `TSTreeMapChartPanel` to take a list of column names and build the (child, parent) pairs.

I figured that for `ChartBuilder` I simplify things and let the caller build a table that has the (child, parent) pairs aka (`Label`, `Parent`) columns.

Expand the `ChartsTreemap` class in the PR and see all the manual table building. This is more or less what `tech.tablesaw.plotly.api.Extract` does except this time I'm using tablesaw and not manual HashMaps, etc.

**Comment by emilianbold** [comment]
It's unclear to me the logic if `ChartBuilder` for treemaps with something like 
```
.dataColumns("Sector", "Industry")
.rowColumns("Ticker")
```

because `Sector` and `Industry` are not unrelated. You have a hierarchy.

**Comment by nielsgron** [comment]
>> I figured that for ChartBuilder I simplify things and let the caller build a table that has the (child, parent) pairs aka (Label, Parent) columns.
No, we don't want the caller to do this.  We want the PlotlyChartBuilder to do this.

>> because Sector and Industry are not unrelated. You have a hierarchy.
They are related and the hierarchy is determined by the order of the columns provided.  col1 is root, with child of col2, which has child of col3.  So, Sector is root with child of Industry.

**Comment by emilianbold** [comment]
OK, let me work some more and I'll update the PR...

**Comment by emilianbold** [comment]
This is the new way I'm thinking this could work:

```java
        ChartBuilder stockBuilder = ChartBuilder.createBuilder()
                .dataTable(treemapTable)
                .chartType(ChartBuilder.CHART_TYPE.TREEMAP)
                .rowColumns("Ticker", "Industry", "Sector")
                .sizeColumn(/* values: */ "ZERO [MarketCap]")
                //TODO: how to aggregate Change?
//                .labelColumns(/* text: */ "Change")
                .colorColumn(/* marker.colors: */ "MEAN [ChangeAsNumber]")
                .layout(1043, 500, false);
```

Note how I use the aggreation function when definin the size and color columns.

Well, `MEAN` is standard. `ZERO` is just a way of saying that parents should not aggregate anything, just set values to 0. (Perhaps a different name would make sense?)

**Pull request merged**
